spring.application.name=notesapp
spring.datasource.url=jdbc:h2:mem:notesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
aws.s3.bucket-name=notesapp-images-26
aws.s3.region=ap-south-1
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB